# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FurnitureFuture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FurnitureFuture
  pod 'SCLAlertView' 
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'iProgressHUD', '~> 1.1.1'

end
